name: Java CI with Gradle and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adoptopenjdk'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Deploy to AWS EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@<EC2_PUBLIC_IP> << EOF
            cd /path/to/your/project
            git pull origin main
            ./gradlew build
            java -jar build/libs/your-app.jar > app.log 2>&1 &
          EOF
